### PR TITLE
first operator generates invalid code when upper bound of lhs is one

### PR DESCRIPTION
**Pull request by besuikerd**

### CODE REVIEW

**Comment by dcharkes** [comment]
When would you use first on an expression of multiplicity `1` or `?`. Isn't it more sensible to reject such programs? (Or we could give a warning, but still allow the program to run. In which case `first` would be a no-op for multiplicities `1` and `?`.)

**Comment by besuikerd** [comment]
probably never. Both options would be okay. I guess rejecting it would be better, since semantically it doesn't make sense to take a first 'element' of a single element

**Comment by dcharkes** [comment]
Well, in some line of thought it does make sense: if the multiplicity is `*` statically, but `1` at runtime, it is a no-op as well. So, in that sense it is more regular to implement it the same way even if you already know statically that the multiplicity is `1`. Of course, as you are certain statically that it is a no-op, a warning (a la dead code) is in order: `TUMany() is multUpper of e1_mult | warning $[Multiplicity mismatch: Expected TUMany() got [e1_mult_u]]@e1`.

P.S. these things should be exercised by tests as well.

**Comment by besuikerd** [comment]
Alright, what about `1.first(3)` ?

**Comment by dcharkes** [comment]
Just `1` itself. Similar to the fact that `no value.first()` and `no value.first(42)` are `no value`.

**Pull request merged**
